// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAh2E8R_2cwme1eWKNbDs0IYGI4DePt7JQ',
    appId: '1:430839922278:web:f62a2068761848346237a7',
    messagingSenderId: '430839922278',
    projectId: 'attendance-app-10dee',
    authDomain: 'attendance-app-10dee.firebaseapp.com',
    storageBucket: 'attendance-app-10dee.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBlKdF5zUvUjvWnA6TxJh-Plu5nHlC2ORg',
    appId: '1:430839922278:android:be05992b1460675b6237a7',
    messagingSenderId: '430839922278',
    projectId: 'attendance-app-10dee',
    storageBucket: 'attendance-app-10dee.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBSHJqCA-D6LFJcGUaSpPvBnYMa9M0Ebm8',
    appId: '1:430839922278:ios:9fedabbd30bc9d676237a7',
    messagingSenderId: '430839922278',
    projectId: 'attendance-app-10dee',
    storageBucket: 'attendance-app-10dee.appspot.com',
    iosBundleId: 'com.asia.attendenceapp',
  );
}
